site_name: Notes Guide Book
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Java:
      - Memory: Java/Memory.md
      - Streams: Java/streams.md
  - AWS:
      - S3: aws/s3.md
  - DSA:
      - Arrays: dsa/arrays.md
  - spring:
      - springboot: spring/springboot.md 
  - data-engineering:
      - basic: data-engineering/basics.md
  - javascript:
      - Arrays: javascript/basics.md
  - LLD:
      - SOLID: LLD/Solid.md         
